### PR TITLE
More examples

### PR DESCRIPTION
**Pull request by chiao45**
This PR will add more examples and group them into three different categories, namely (1) beginner, (2) intermediate, and (3) advanced. In addition, this PR will update the documentation according to new examples.

### CODE REVIEW

**Comment by xmjiao** [comment]
In `demo_gmreshif.cpp`, I think the following statement is unnecessary: 
"The testing system comes from the Stokes equations discretized using the
  Taylor-Hood elements. Hence, the problem is a symmetric saddle-point system."

The demo should work for any nonsingular systems.

**Comment by chiao45** [comment]
> In `demo_gmreshif.cpp`, I think the following statement is unnecessary:
> "The testing system comes from the Stokes equations discretized using the
> Taylor-Hood elements. Hence, the problem is a symmetric saddle-point system."
> 
> The demo should work for any nonsingular systems.

Just updated the PR and removed "symmetric systems."

**Comment by xmjiao** [comment]
> > In `demo_gmreshif.cpp`, I think the following statement is unnecessary:
> > "The testing system comes from the Stokes equations discretized using the
> > Taylor-Hood elements. Hence, the problem is a symmetric saddle-point system."
> > The demo should work for any nonsingular systems.
> 
> @xmjiao Just updated the PR and removed "symmetric systems."

We should remove the complete sentence regarding Stokes equations. This was about the example input matrix in `demo_inputs` and it is already explained there. The demo functions have nothing to do with Stokes equations.

Please also remove the similar mentioning in `examples.doc`.

Please change `readme.txt` to `README.txt` under `demo_inputs` and also explain how the users can replace the matrices and RHS vector with their own examples.

**Comment by xmjiao** [comment]
Probably should have an example to demonstrate complex arithmetic.

**Comment by chiao45** [comment]
> > > In `demo_gmreshif.cpp`, I think the following statement is unnecessary:
> > > "The testing system comes from the Stokes equations discretized using the
> > > Taylor-Hood elements. Hence, the problem is a symmetric saddle-point system."
> > > The demo should work for any nonsingular systems.
> > 
> > 
> > @xmjiao Just updated the PR and removed "symmetric systems."
> 
> We should remove the complete sentence regarding Stokes equations. This was about the example input matrix in `demo_inputs` and it is already explained there. The demo functions have nothing to do with Stokes equations.
> 
> Please also remove the similar mentioning in `examples.doc`.
> 
> Please change `readme.txt` to `README.txt` under `demo_inputs` and also explain how the users can replace the matrices and RHS vector with their own examples.

@xmjiao I just updated the PR for this part.

**Comment by chiao45** [comment]
> Probably should have an example to demonstrate complex arithmetic.

@xmjiao Just updated PR for this.

**Review by xmjiao — APPROVED** [review]

**Pull request merged**
